apiversion: app/V1
kind: deployment
metadata:
 name: app-deployment
   label:
     -name: my-app
spec:
 template:
   metadata:
     -name: app-deployment
       label:
       -app: my-app
containers: 
   -name: cbz-containers
     -image: httpd
   ports
   -containersPort: 80
   